### ISSUE TITLE
Is still alive the project?

### ISSUE THREAD

**Issue by Allan-Nava** [willowtreeapps/rocute#60]

**Comment by Allan-Nava** [comment]
any news?

**Comment by madeleine-adams** [comment]
I'm the only one keeping the project up to date right now, and I haven't had time to look at it in a few months. If you're having issues with anything or have suggestions, please let me know.

**Comment by Allan-Nava** [comment]
I'm trying to develop a roku application, any suggestion?

**Comment by madeleine-adams** [comment]
Yes, there are some great video tutorials on the Roku Developers website here: https://developer.roku.com/en-gb/videos/courses/rsg/intro.md

**Comment by Allan-Nava** [comment]
I know i tried, but the problem is the navigation like appbar control in iOS
